apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-28T22:09:06Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "289"
  uid: f997f810-eddc-4dc6-b174-5eae43da2418
data:
  Corefile: |
    .:53 {
        rewrite stop type AAAA A
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153

        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
