---
all:
  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/ansible_ed25519

  children:
    k8s_control_planes:
      hosts:
        k8s-control-01:
          ansible_host: 10.8.0.101
          proxmox_vmid: 300
          proxmox_node: mgmt1

    k8s_workers:
      hosts:
        k8s-worker-01:
          ansible_host: 10.8.1.101
          proxmox_vmid: 301
          proxmox_node: mgmt1

        k8s-worker-02:
          ansible_host: 10.8.1.102
          proxmox_vmid: 302
          proxmox_node: mgmt2

        k8s-worker-03:
          ansible_host: 10.8.1.103
          proxmox_vmid: 303
          proxmox_node: mgmt3

    kubernetes:
      children:
        k8s_control_planes: {}
        k8s_workers: {}
